[package]
name = "pokemon-api"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio-native-tls"] }

